"""add numero_lote to lotes

Revision ID: f5a9105e624e
Revises: bf01a0a532cd
Create Date: 2026-04-18 18:15:03.807929

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f5a9105e624e'
down_revision = 'bf01a0a532cd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('numero_lote', sa.String(length=60), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lotes', schema=None) as batch_op:
        batch_op.drop_column('numero_lote')

    # ### end Alembic commands ###
